Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'drual-web'
    web.vm.box_url = "ubuntu/trusty64"
	web.vm.network "private_network", ip: "192.168.0.1"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "skurikhin-web"]
      v.customize ["modifyvm", :id, "--nic2", "bridged"] 
      v.customize ["modifyvm", :id, "--nic1", "nat"]
    end
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = 'drupal-db'
    db.vm.box_url = "ubuntu/trusty64"
    web.vm.network "private_network", ip: "192.168.0.2"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
      v.customize ["modifyvm", :id, "--name", "skurikhin-db"]
      v.customize ["modifyvm", :id, "--nic2", "bridged"]
      v.customize ["modifyvm", :id, "--nic1", "nat"]
    end
    db.vm.provision "shell", path: "db.sh"
  end
end