Vagrant.configure("2") do |config|
  config.vm.define "web" do |subconfig|
#    subconfig.vm.box = "hashicorp/precise32"
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.10.9"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 2]
	  v.customize ["modifyvm", :id, "--name", "web_drupal"]
    end
    subconfig.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |subconfig|
#    subconfig.vm.box = "hashicorp/precise32"
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.10.10"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 2]
	  v.customize ["modifyvm", :id, "--name", "db_drupal"]
    end
    subconfig.vm.provision "shell", path: "db.sh"
  end
end