Vagrant.configure("2") do |config|
  config.vm.define "web" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.50.5"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "web"]
	  # proxy dla wirtualnej maszyny, bez tego nie ma połączenia z siecią 
	  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	  v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    subconfig.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.50.6"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "db"]
	  v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	  v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    subconfig.vm.provision "shell", path: "db.sh"
  end
end
