Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/trusty64"
    web.vm.hostname = 'drupal-web'
    web.vm.box_url = "ubuntu/trusty64"
	web.vm.network "forwarded_port", guest: 80, host: 8080
	web.vm.network "private_network", ip: "192.168.1.100"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
#      v.customize ["modifyvm", :id, "--bridgeadapter2", "Realtek PCIe GBE Family Controller"]
    end
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/trusty64"
    db.vm.hostname = 'drupal-db'
    db.vm.box_url = "ubuntu/trusty64"
	db.vm.network "private_network", ip: "192.168.1.101"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
#      v.customize ["modifyvm", :id, "--bridgeadapter2", "Realtek PCIe GBE Family Controller"]
    end
    db.vm.provision "shell", path: "db.sh"
  end
end
