Vagrant.configure("2") do |config|
  config.vm.define "web" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "10.69.69.2"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "SerwerWeb"]
    end
    subconfig.vm.provision "shell", path: "WEB.sh"
  end

  config.vm.define "db" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "10.69.69.3"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "SerwerDB"]
    end
    subconfig.vm.provision "shell", path: "DB.sh"
  end
end