
if ! File.exists?('./resources/NDP452-KB2901907-x86-x64-AllOS-ENU.exe')
  puts '.Net 4.5.2 installer could not be found!'
  puts "Please run:\n  wget http://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
  exit 1
end

if ! File.exists?('./resources/Octopus.Tentacle.2.6.0.778-x64.msi')
  puts 'Octopus Tentacle installer could not be found!'
  puts "Please run:\n  wget http://download.octopusdeploy.com/octopus/Octopus.Tentacle.2.6.0.778-x64.msi"
  exit 1
end

Vagrant.configure("2") do |config|

  config.vm.define "node01" do |subconfig|
 
	subconfig.vm.box = "ferventcoder/win2008r2-x64-nocm"
	subconfig.vm.guest = :windows
	subconfig.vm.communicator = "winrm"
	subconfig.vm.network "private_network", ip: "192.168.10.10"
	subconfig.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "node01"]
	  
    end
	
	subconfig.vm.provision :shell, path: "scripts/install-iis.cmd"
	subconfig.vm.provision :shell, path: "scripts/delete-default-iis-website.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net-45.cmd"
	subconfig.vm.provision :shell, path: "scripts/install-octopus-tentacle.cmd"
	subconfig.vm.provision :shell, path: "scripts/configure-octopus-tentacle.cmd"
	
	end

  config.vm.define "node02" do |subconfig|
 
	subconfig.vm.box = "ferventcoder/win2008r2-x64-nocm"
	subconfig.vm.guest = :windows
	subconfig.vm.communicator = "winrm"
	subconfig.vm.network "private_network", ip: "192.168.10.20"
	subconfig.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "node02"]
	  
    end
	
	subconfig.vm.provision :shell, path: "scripts/install-iis.cmd"
	subconfig.vm.provision :shell, path: "scripts/delete-default-iis-website.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net-45.cmd"
	subconfig.vm.provision :shell, path: "scripts/install-octopus-tentacle.cmd"
	subconfig.vm.provision :shell, path: "scripts/configure-octopus-tentacle.cmd"
	
	end
	
	 config.vm.define "node03" do |subconfig|
 
	subconfig.vm.box = "ferventcoder/win2008r2-x64-nocm"
	subconfig.vm.guest = :windows
	subconfig.vm.communicator = "winrm"
	subconfig.vm.network "private_network", ip: "192.168.10.30"
	subconfig.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "node03"]
	  
    end
	
	subconfig.vm.provision :shell, path: "scripts/install-iis.cmd"
	subconfig.vm.provision :shell, path: "scripts/delete-default-iis-website.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net.ps1"
	subconfig.vm.provision :shell, path: "scripts/install-dot-net-45.cmd"
	subconfig.vm.provision :shell, path: "scripts/install-octopus-tentacle.cmd"
	subconfig.vm.provision :shell, path: "scripts/configure-octopus-tentacle.cmd"
	
	end
end
