Vagrant.configure("2") do |config|
  config.vm.define "web" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.56.5"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "drupal-web"]
    end
    subconfig.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |subconfig|
	subconfig.vm.box = "ubuntu/trusty64"
	subconfig.vm.network "private_network", ip: "192.168.56.6"
	subconfig.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "drupal-db"]
    end
    subconfig.vm.provision "shell", path: "db.sh"
  end
end