Vagrant.configure("2") do |config|
   config.vm.define "web" do |web|
     web.vm.box = "ubuntu/trusty64"
     web.vm.hostname = 'drupal-web'
     web.vm.network "private_network", ip: "192.168.50.1"
 	web.vm.network "forwarded_port", guest: 80, host: 8000
     web.vm.box_url = "ubuntu/trusty64"
 
     web.vm.provider :virtualbox do |v|
       v.customize ["modifyvm", :id, "--memory", 1024]
       v.customize ["modifyvm", :id, "--cpus", 1]
       v.customize ["modifyvm", :id, "--name", "dev-web"]
     end
     web.vm.provision "shell", path: "web.sh"
   end
     config.vm.define "db" do |db|
     db.vm.box = "ubuntu/trusty64"
     db.vm.hostname = 'drupal-db'
     db.vm.network "private_network", ip: "192.168.50.2"
     db.vm.box_url = "ubuntu/trusty64"
 
     db.vm.provider :virtualbox do |v|
       v.customize ["modifyvm", :id, "--memory", 512]
       v.customize ["modifyvm", :id, "--cpus", 1]
       v.customize ["modifyvm", :id, "--name", "dev-db"]
     end
     db.vm.provision "shell", path: "db.sh"
   end
 end