Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "hashicorp/precise32"
	web.vm.box = "ubuntu/trusty64"
	web.vm.network "private_network", ip: "192.168.33.3"
	web.vm.network "forwarded_port", guest: 80, host: 8080

	web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "dev-web"]
	  v.customize ["modifyvm", :id, "--bridgeadapter2", "enp0s25"]
	  v.customize ["modifyvm", :id, "--nic1", "nat"]
    end
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box = "hashicorp/precise32"
	db.vm.box = "ubuntu/trusty64"
	db.vm.network "private_network", ip: "192.168.33.4"
	db.vm.network "forwarded_port", guest: 80, host: 8080

	db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--cpus", 1]
	  v.customize ["modifyvm", :id, "--name", "dev-db"]
	  v.customize ["modifyvm", :id, "--bridgeadapter2", "enp0s25"]
	  v.customize ["modifyvm", :id, "--nic1", "nat"]
    end
    db.vm.provision "shell", path: "db.sh"
  end
end